### ISSUE TITLE
ironwood Application labels aren't unique

### ISSUE THREAD

**Issue by eazaika** [edx/edx-zoom#20]
In Django 1.11.29 gets error:
'''
Traceback (most recent call last):
  File "/edx/bin/manage.edxapp", line 120, in <module>
    startup.run()
  File "/edx/app/edxapp/edx-platform/lms/startup.py", line 19, in run
    django.setup()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/apps/registry.py", line 89, in populate
    "duplicates: %s" % app_config.label)
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: edx_zoom
'''
and no one really duplicate in envs settings

**Comment by eazaika** [comment]
Oh, sorry, the problem is about method of installing - to fix it use pip install -e
